#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Utils
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FT")]
	public partial class ReceiptsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertDIC_ReceiptsAuditLevel(DIC_ReceiptsAuditLevel instance);
    partial void UpdateDIC_ReceiptsAuditLevel(DIC_ReceiptsAuditLevel instance);
    partial void DeleteDIC_ReceiptsAuditLevel(DIC_ReceiptsAuditLevel instance);
    #endregion
		
		public ReceiptsDataContext() : 
				base("", mappingSource)
		{
			OnCreated();
		}
		
		public ReceiptsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReceiptsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReceiptsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReceiptsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DIC_ReceiptsAuditLevel> DIC_ReceiptsAuditLevel
		{
			get
			{
				return this.GetTable<DIC_ReceiptsAuditLevel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIC_ReceiptsAuditLevel")]
	public partial class DIC_ReceiptsAuditLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ReceiptsCode;
		
		private string _ReceiptsEnglishName;
		
		private string _ReceiptsChineseName;
		
		private string _AuditLevel;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReceiptsCodeChanging(string value);
    partial void OnReceiptsCodeChanged();
    partial void OnReceiptsEnglishNameChanging(string value);
    partial void OnReceiptsEnglishNameChanged();
    partial void OnReceiptsChineseNameChanging(string value);
    partial void OnReceiptsChineseNameChanged();
    partial void OnAuditLevelChanging(string value);
    partial void OnAuditLevelChanged();
    #endregion
		
		public DIC_ReceiptsAuditLevel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptsCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ReceiptsCode
		{
			get
			{
				return this._ReceiptsCode;
			}
			set
			{
				if ((this._ReceiptsCode != value))
				{
					this.OnReceiptsCodeChanging(value);
					this.SendPropertyChanging();
					this._ReceiptsCode = value;
					this.SendPropertyChanged("ReceiptsCode");
					this.OnReceiptsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptsEnglishName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceiptsEnglishName
		{
			get
			{
				return this._ReceiptsEnglishName;
			}
			set
			{
				if ((this._ReceiptsEnglishName != value))
				{
					this.OnReceiptsEnglishNameChanging(value);
					this.SendPropertyChanging();
					this._ReceiptsEnglishName = value;
					this.SendPropertyChanged("ReceiptsEnglishName");
					this.OnReceiptsEnglishNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptsChineseName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceiptsChineseName
		{
			get
			{
				return this._ReceiptsChineseName;
			}
			set
			{
				if ((this._ReceiptsChineseName != value))
				{
					this.OnReceiptsChineseNameChanging(value);
					this.SendPropertyChanging();
					this._ReceiptsChineseName = value;
					this.SendPropertyChanged("ReceiptsChineseName");
					this.OnReceiptsChineseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditLevel", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AuditLevel
		{
			get
			{
				return this._AuditLevel;
			}
			set
			{
				if ((this._AuditLevel != value))
				{
					this.OnAuditLevelChanging(value);
					this.SendPropertyChanging();
					this._AuditLevel = value;
					this.SendPropertyChanged("AuditLevel");
					this.OnAuditLevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
