#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Utils
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FT")]
	public partial class UnitTransDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_MaterialUnitRelation(T_MaterialUnitRelation instance);
    partial void UpdateT_MaterialUnitRelation(T_MaterialUnitRelation instance);
    partial void DeleteT_MaterialUnitRelation(T_MaterialUnitRelation instance);
    #endregion
		
		public UnitTransDataContext() : 
				base("", mappingSource)
		{
			OnCreated();
		}
		
		public UnitTransDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitTransDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitTransDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitTransDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_MaterialUnitRelation> T_MaterialUnitRelation
		{
			get
			{
				return this.GetTable<T_MaterialUnitRelation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_MaterialUnitRelation")]
	public partial class T_MaterialUnitRelation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaterialID;
		
		private string _MaterialVersion;
		
		private string _MaterialUnitCode;
		
		private string _MaterialUnit;
		
		private string _PurchaseUnitCode;
		
		private string _PurchaseUnit;
		
		private double _PurchaseRelation;
		
		private string _StockUnitCode;
		
		private string _StockUnit;
		
		private double _StockRelation;
		
		private string _GetUnitCode;
		
		private string _GetUnit;
		
		private double _GetRelation;
		
		private string _ProductionUnitCode;
		
		private string _ProductionUnit;
		
		private double _ProductionRelation;
		
		private string _StockInUnitCode;
		
		private string _StockInUnit;
		
		private double _StockInRelation;
		
		private string _StockOutUnitCode;
		
		private string _StockOutUnit;
		
		private double _StockOutRelation;
		
		private string _SalesUnitCode;
		
		private string _SalesUnit;
		
		private double _SalesRelation;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaterialIDChanging(string value);
    partial void OnMaterialIDChanged();
    partial void OnMaterialVersionChanging(string value);
    partial void OnMaterialVersionChanged();
    partial void OnMaterialUnitCodeChanging(string value);
    partial void OnMaterialUnitCodeChanged();
    partial void OnMaterialUnitChanging(string value);
    partial void OnMaterialUnitChanged();
    partial void OnPurchaseUnitCodeChanging(string value);
    partial void OnPurchaseUnitCodeChanged();
    partial void OnPurchaseUnitChanging(string value);
    partial void OnPurchaseUnitChanged();
    partial void OnPurchaseRelationChanging(double value);
    partial void OnPurchaseRelationChanged();
    partial void OnStockUnitCodeChanging(string value);
    partial void OnStockUnitCodeChanged();
    partial void OnStockUnitChanging(string value);
    partial void OnStockUnitChanged();
    partial void OnStockRelationChanging(double value);
    partial void OnStockRelationChanged();
    partial void OnGetUnitCodeChanging(string value);
    partial void OnGetUnitCodeChanged();
    partial void OnGetUnitChanging(string value);
    partial void OnGetUnitChanged();
    partial void OnGetRelationChanging(double value);
    partial void OnGetRelationChanged();
    partial void OnProductionUnitCodeChanging(string value);
    partial void OnProductionUnitCodeChanged();
    partial void OnProductionUnitChanging(string value);
    partial void OnProductionUnitChanged();
    partial void OnProductionRelationChanging(double value);
    partial void OnProductionRelationChanged();
    partial void OnStockInUnitCodeChanging(string value);
    partial void OnStockInUnitCodeChanged();
    partial void OnStockInUnitChanging(string value);
    partial void OnStockInUnitChanged();
    partial void OnStockInRelationChanging(double value);
    partial void OnStockInRelationChanged();
    partial void OnStockOutUnitCodeChanging(string value);
    partial void OnStockOutUnitCodeChanged();
    partial void OnStockOutUnitChanging(string value);
    partial void OnStockOutUnitChanged();
    partial void OnStockOutRelationChanging(double value);
    partial void OnStockOutRelationChanged();
    partial void OnSalesUnitCodeChanging(string value);
    partial void OnSalesUnitCodeChanged();
    partial void OnSalesUnitChanging(string value);
    partial void OnSalesUnitChanged();
    partial void OnSalesRelationChanging(double value);
    partial void OnSalesRelationChanged();
    #endregion
		
		public T_MaterialUnitRelation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialID", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaterialID
		{
			get
			{
				return this._MaterialID;
			}
			set
			{
				if ((this._MaterialID != value))
				{
					this.OnMaterialIDChanging(value);
					this.SendPropertyChanging();
					this._MaterialID = value;
					this.SendPropertyChanged("MaterialID");
					this.OnMaterialIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialVersion", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaterialVersion
		{
			get
			{
				return this._MaterialVersion;
			}
			set
			{
				if ((this._MaterialVersion != value))
				{
					this.OnMaterialVersionChanging(value);
					this.SendPropertyChanging();
					this._MaterialVersion = value;
					this.SendPropertyChanged("MaterialVersion");
					this.OnMaterialVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaterialUnitCode
		{
			get
			{
				return this._MaterialUnitCode;
			}
			set
			{
				if ((this._MaterialUnitCode != value))
				{
					this.OnMaterialUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._MaterialUnitCode = value;
					this.SendPropertyChanged("MaterialUnitCode");
					this.OnMaterialUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string MaterialUnit
		{
			get
			{
				return this._MaterialUnit;
			}
			set
			{
				if ((this._MaterialUnit != value))
				{
					this.OnMaterialUnitChanging(value);
					this.SendPropertyChanging();
					this._MaterialUnit = value;
					this.SendPropertyChanged("MaterialUnit");
					this.OnMaterialUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PurchaseUnitCode
		{
			get
			{
				return this._PurchaseUnitCode;
			}
			set
			{
				if ((this._PurchaseUnitCode != value))
				{
					this.OnPurchaseUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._PurchaseUnitCode = value;
					this.SendPropertyChanged("PurchaseUnitCode");
					this.OnPurchaseUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string PurchaseUnit
		{
			get
			{
				return this._PurchaseUnit;
			}
			set
			{
				if ((this._PurchaseUnit != value))
				{
					this.OnPurchaseUnitChanging(value);
					this.SendPropertyChanging();
					this._PurchaseUnit = value;
					this.SendPropertyChanged("PurchaseUnit");
					this.OnPurchaseUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseRelation", DbType="Float NOT NULL")]
		public double PurchaseRelation
		{
			get
			{
				return this._PurchaseRelation;
			}
			set
			{
				if ((this._PurchaseRelation != value))
				{
					this.OnPurchaseRelationChanging(value);
					this.SendPropertyChanging();
					this._PurchaseRelation = value;
					this.SendPropertyChanged("PurchaseRelation");
					this.OnPurchaseRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string StockUnitCode
		{
			get
			{
				return this._StockUnitCode;
			}
			set
			{
				if ((this._StockUnitCode != value))
				{
					this.OnStockUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._StockUnitCode = value;
					this.SendPropertyChanged("StockUnitCode");
					this.OnStockUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string StockUnit
		{
			get
			{
				return this._StockUnit;
			}
			set
			{
				if ((this._StockUnit != value))
				{
					this.OnStockUnitChanging(value);
					this.SendPropertyChanging();
					this._StockUnit = value;
					this.SendPropertyChanged("StockUnit");
					this.OnStockUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockRelation", DbType="Float NOT NULL")]
		public double StockRelation
		{
			get
			{
				return this._StockRelation;
			}
			set
			{
				if ((this._StockRelation != value))
				{
					this.OnStockRelationChanging(value);
					this.SendPropertyChanging();
					this._StockRelation = value;
					this.SendPropertyChanged("StockRelation");
					this.OnStockRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string GetUnitCode
		{
			get
			{
				return this._GetUnitCode;
			}
			set
			{
				if ((this._GetUnitCode != value))
				{
					this.OnGetUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._GetUnitCode = value;
					this.SendPropertyChanged("GetUnitCode");
					this.OnGetUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string GetUnit
		{
			get
			{
				return this._GetUnit;
			}
			set
			{
				if ((this._GetUnit != value))
				{
					this.OnGetUnitChanging(value);
					this.SendPropertyChanging();
					this._GetUnit = value;
					this.SendPropertyChanged("GetUnit");
					this.OnGetUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetRelation", DbType="Float NOT NULL")]
		public double GetRelation
		{
			get
			{
				return this._GetRelation;
			}
			set
			{
				if ((this._GetRelation != value))
				{
					this.OnGetRelationChanging(value);
					this.SendPropertyChanging();
					this._GetRelation = value;
					this.SendPropertyChanged("GetRelation");
					this.OnGetRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductionUnitCode
		{
			get
			{
				return this._ProductionUnitCode;
			}
			set
			{
				if ((this._ProductionUnitCode != value))
				{
					this.OnProductionUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductionUnitCode = value;
					this.SendPropertyChanged("ProductionUnitCode");
					this.OnProductionUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ProductionUnit
		{
			get
			{
				return this._ProductionUnit;
			}
			set
			{
				if ((this._ProductionUnit != value))
				{
					this.OnProductionUnitChanging(value);
					this.SendPropertyChanging();
					this._ProductionUnit = value;
					this.SendPropertyChanged("ProductionUnit");
					this.OnProductionUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionRelation", DbType="Float NOT NULL")]
		public double ProductionRelation
		{
			get
			{
				return this._ProductionRelation;
			}
			set
			{
				if ((this._ProductionRelation != value))
				{
					this.OnProductionRelationChanging(value);
					this.SendPropertyChanging();
					this._ProductionRelation = value;
					this.SendPropertyChanged("ProductionRelation");
					this.OnProductionRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockInUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string StockInUnitCode
		{
			get
			{
				return this._StockInUnitCode;
			}
			set
			{
				if ((this._StockInUnitCode != value))
				{
					this.OnStockInUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._StockInUnitCode = value;
					this.SendPropertyChanged("StockInUnitCode");
					this.OnStockInUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockInUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string StockInUnit
		{
			get
			{
				return this._StockInUnit;
			}
			set
			{
				if ((this._StockInUnit != value))
				{
					this.OnStockInUnitChanging(value);
					this.SendPropertyChanging();
					this._StockInUnit = value;
					this.SendPropertyChanged("StockInUnit");
					this.OnStockInUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockInRelation", DbType="Float NOT NULL")]
		public double StockInRelation
		{
			get
			{
				return this._StockInRelation;
			}
			set
			{
				if ((this._StockInRelation != value))
				{
					this.OnStockInRelationChanging(value);
					this.SendPropertyChanging();
					this._StockInRelation = value;
					this.SendPropertyChanged("StockInRelation");
					this.OnStockInRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockOutUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string StockOutUnitCode
		{
			get
			{
				return this._StockOutUnitCode;
			}
			set
			{
				if ((this._StockOutUnitCode != value))
				{
					this.OnStockOutUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._StockOutUnitCode = value;
					this.SendPropertyChanged("StockOutUnitCode");
					this.OnStockOutUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockOutUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string StockOutUnit
		{
			get
			{
				return this._StockOutUnit;
			}
			set
			{
				if ((this._StockOutUnit != value))
				{
					this.OnStockOutUnitChanging(value);
					this.SendPropertyChanging();
					this._StockOutUnit = value;
					this.SendPropertyChanged("StockOutUnit");
					this.OnStockOutUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockOutRelation", DbType="Float NOT NULL")]
		public double StockOutRelation
		{
			get
			{
				return this._StockOutRelation;
			}
			set
			{
				if ((this._StockOutRelation != value))
				{
					this.OnStockOutRelationChanging(value);
					this.SendPropertyChanging();
					this._StockOutRelation = value;
					this.SendPropertyChanged("StockOutRelation");
					this.OnStockOutRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesUnitCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SalesUnitCode
		{
			get
			{
				return this._SalesUnitCode;
			}
			set
			{
				if ((this._SalesUnitCode != value))
				{
					this.OnSalesUnitCodeChanging(value);
					this.SendPropertyChanging();
					this._SalesUnitCode = value;
					this.SendPropertyChanged("SalesUnitCode");
					this.OnSalesUnitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesUnit", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SalesUnit
		{
			get
			{
				return this._SalesUnit;
			}
			set
			{
				if ((this._SalesUnit != value))
				{
					this.OnSalesUnitChanging(value);
					this.SendPropertyChanging();
					this._SalesUnit = value;
					this.SendPropertyChanged("SalesUnit");
					this.OnSalesUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRelation", DbType="Float NOT NULL")]
		public double SalesRelation
		{
			get
			{
				return this._SalesRelation;
			}
			set
			{
				if ((this._SalesRelation != value))
				{
					this.OnSalesRelationChanging(value);
					this.SendPropertyChanging();
					this._SalesRelation = value;
					this.SendPropertyChanged("SalesRelation");
					this.OnSalesRelationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
