#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Conference")]
	public partial class DataClassesCFDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_User(T_User instance);
    partial void UpdateT_User(T_User instance);
    partial void DeleteT_User(T_User instance);
    partial void InsertT_ConferenceInfo(T_ConferenceInfo instance);
    partial void UpdateT_ConferenceInfo(T_ConferenceInfo instance);
    partial void DeleteT_ConferenceInfo(T_ConferenceInfo instance);
    #endregion
		
		public DataClassesCFDataContext() : 
				base(global::Conference_DAL.Properties.Settings.Default.ConferenceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCFDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCFDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_User> T_User
		{
			get
			{
				return this.GetTable<T_User>();
			}
		}
		
		public System.Data.Linq.Table<T_ConferenceInfo> T_ConferenceInfo
		{
			get
			{
				return this.GetTable<T_ConferenceInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_User")]
	public partial class T_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<bool> _IsInnerUser;
		
		private System.Nullable<bool> _IsLogoutUser;
		
		private string _CreateOperatorName;
		
		private string _CreateOperatorID;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private string _LastModiOperatorName;
		
		private string _LastModiOperatorID;
		
		private System.Nullable<System.DateTime> _LastModiTime;
		
		private string _Notes;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIsInnerUserChanging(System.Nullable<bool> value);
    partial void OnIsInnerUserChanged();
    partial void OnIsLogoutUserChanging(System.Nullable<bool> value);
    partial void OnIsLogoutUserChanged();
    partial void OnCreateOperatorNameChanging(string value);
    partial void OnCreateOperatorNameChanged();
    partial void OnCreateOperatorIDChanging(string value);
    partial void OnCreateOperatorIDChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnLastModiOperatorNameChanging(string value);
    partial void OnLastModiOperatorNameChanged();
    partial void OnLastModiOperatorIDChanging(string value);
    partial void OnLastModiOperatorIDChanged();
    partial void OnLastModiTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModiTimeChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public T_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInnerUser", DbType="Bit")]
		public System.Nullable<bool> IsInnerUser
		{
			get
			{
				return this._IsInnerUser;
			}
			set
			{
				if ((this._IsInnerUser != value))
				{
					this.OnIsInnerUserChanging(value);
					this.SendPropertyChanging();
					this._IsInnerUser = value;
					this.SendPropertyChanged("IsInnerUser");
					this.OnIsInnerUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogoutUser", DbType="Bit")]
		public System.Nullable<bool> IsLogoutUser
		{
			get
			{
				return this._IsLogoutUser;
			}
			set
			{
				if ((this._IsLogoutUser != value))
				{
					this.OnIsLogoutUserChanging(value);
					this.SendPropertyChanging();
					this._IsLogoutUser = value;
					this.SendPropertyChanged("IsLogoutUser");
					this.OnIsLogoutUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOperatorName", DbType="NVarChar(20)")]
		public string CreateOperatorName
		{
			get
			{
				return this._CreateOperatorName;
			}
			set
			{
				if ((this._CreateOperatorName != value))
				{
					this.OnCreateOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._CreateOperatorName = value;
					this.SendPropertyChanged("CreateOperatorName");
					this.OnCreateOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOperatorID", DbType="NVarChar(20)")]
		public string CreateOperatorID
		{
			get
			{
				return this._CreateOperatorID;
			}
			set
			{
				if ((this._CreateOperatorID != value))
				{
					this.OnCreateOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._CreateOperatorID = value;
					this.SendPropertyChanged("CreateOperatorID");
					this.OnCreateOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModiOperatorName", DbType="NVarChar(20)")]
		public string LastModiOperatorName
		{
			get
			{
				return this._LastModiOperatorName;
			}
			set
			{
				if ((this._LastModiOperatorName != value))
				{
					this.OnLastModiOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._LastModiOperatorName = value;
					this.SendPropertyChanged("LastModiOperatorName");
					this.OnLastModiOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModiOperatorID", DbType="NVarChar(20)")]
		public string LastModiOperatorID
		{
			get
			{
				return this._LastModiOperatorID;
			}
			set
			{
				if ((this._LastModiOperatorID != value))
				{
					this.OnLastModiOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._LastModiOperatorID = value;
					this.SendPropertyChanged("LastModiOperatorID");
					this.OnLastModiOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModiTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModiTime
		{
			get
			{
				return this._LastModiTime;
			}
			set
			{
				if ((this._LastModiTime != value))
				{
					this.OnLastModiTimeChanging(value);
					this.SendPropertyChanging();
					this._LastModiTime = value;
					this.SendPropertyChanged("LastModiTime");
					this.OnLastModiTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(512)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_ConferenceInfo")]
	public partial class T_ConferenceInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ConferenceID;
		
		private string _ConferenceName;
		
		private System.Nullable<System.DateTime> _ConferenceDate;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private string _AppointmentPeople;
		
		private string _ParticipantsPeople;
		
		private string _ConferenceTopics;
		
		private string _ConferencePlace;
		
		private string _Notes;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConferenceIDChanging(string value);
    partial void OnConferenceIDChanged();
    partial void OnConferenceNameChanging(string value);
    partial void OnConferenceNameChanged();
    partial void OnConferenceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnConferenceDateChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnAppointmentPeopleChanging(string value);
    partial void OnAppointmentPeopleChanged();
    partial void OnParticipantsPeopleChanging(string value);
    partial void OnParticipantsPeopleChanged();
    partial void OnConferenceTopicsChanging(string value);
    partial void OnConferenceTopicsChanged();
    partial void OnConferencePlaceChanging(string value);
    partial void OnConferencePlaceChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public T_ConferenceInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferenceID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ConferenceID
		{
			get
			{
				return this._ConferenceID;
			}
			set
			{
				if ((this._ConferenceID != value))
				{
					this.OnConferenceIDChanging(value);
					this.SendPropertyChanging();
					this._ConferenceID = value;
					this.SendPropertyChanged("ConferenceID");
					this.OnConferenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferenceName", DbType="NVarChar(100)")]
		public string ConferenceName
		{
			get
			{
				return this._ConferenceName;
			}
			set
			{
				if ((this._ConferenceName != value))
				{
					this.OnConferenceNameChanging(value);
					this.SendPropertyChanging();
					this._ConferenceName = value;
					this.SendPropertyChanged("ConferenceName");
					this.OnConferenceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferenceDate", DbType="Date")]
		public System.Nullable<System.DateTime> ConferenceDate
		{
			get
			{
				return this._ConferenceDate;
			}
			set
			{
				if ((this._ConferenceDate != value))
				{
					this.OnConferenceDateChanging(value);
					this.SendPropertyChanging();
					this._ConferenceDate = value;
					this.SendPropertyChanged("ConferenceDate");
					this.OnConferenceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppointmentPeople", DbType="NVarChar(200)")]
		public string AppointmentPeople
		{
			get
			{
				return this._AppointmentPeople;
			}
			set
			{
				if ((this._AppointmentPeople != value))
				{
					this.OnAppointmentPeopleChanging(value);
					this.SendPropertyChanging();
					this._AppointmentPeople = value;
					this.SendPropertyChanged("AppointmentPeople");
					this.OnAppointmentPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParticipantsPeople", DbType="NVarChar(200)")]
		public string ParticipantsPeople
		{
			get
			{
				return this._ParticipantsPeople;
			}
			set
			{
				if ((this._ParticipantsPeople != value))
				{
					this.OnParticipantsPeopleChanging(value);
					this.SendPropertyChanging();
					this._ParticipantsPeople = value;
					this.SendPropertyChanged("ParticipantsPeople");
					this.OnParticipantsPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferenceTopics", DbType="NVarChar(200)")]
		public string ConferenceTopics
		{
			get
			{
				return this._ConferenceTopics;
			}
			set
			{
				if ((this._ConferenceTopics != value))
				{
					this.OnConferenceTopicsChanging(value);
					this.SendPropertyChanging();
					this._ConferenceTopics = value;
					this.SendPropertyChanged("ConferenceTopics");
					this.OnConferenceTopicsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferencePlace", DbType="NVarChar(50)")]
		public string ConferencePlace
		{
			get
			{
				return this._ConferencePlace;
			}
			set
			{
				if ((this._ConferencePlace != value))
				{
					this.OnConferencePlaceChanging(value);
					this.SendPropertyChanging();
					this._ConferencePlace = value;
					this.SendPropertyChanged("ConferencePlace");
					this.OnConferencePlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(200)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
